services:
  astra_legacy:
    build:
      dockerfile: Dockerfile
    command: ros2 launch astra_camera astra_pro.launch.py
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
